project_id = "ubfwllsoopfphnqtdfaq"

[functions.generate-certificate]
verify_jwt = false

[functions.create-test-users]
verify_jwt = false

[functions.check-expiring-subscriptions]
verify_jwt = false

[functions.send-suspension-email]
verify_jwt = false
